import type { Metadata } from "next";
import {
  Frank_Ruhl_Libre,
  Fraunces,
  Geist,
  Geist_Mono,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const titleLatin = Fraunces({
  variable: "--font-title-latin",
  subsets: ["latin"],
  weight: ["700"],
});

const titleHebrew = Frank_Ruhl_Libre({
  variable: "--font-title-hebrew",
  subsets: ["hebrew", "latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${titleLatin.variable} ${titleHebrew.variable} antialiased min-h-screen bg-green-100`}
      >
        {children}
      </body>
    </html>
  );
}
